# Generated by Django 4.1.2 on 2022-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_buku_halaman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='penerbit',
        ),
        migrations.AddField(
            model_name='buku',
            name='deskripsi',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
