# Generated by Django 4.1.2 on 2022-12-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0003_remove_buku_penerbit_buku_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='deskripsi',
            field=models.TextField(),
        ),
    ]
